default:
  image: buildkite/puppeteer:5.2.1
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .yarn
  before_script:
    - yarn install --cache-folder .yarn --frozen-lockfile

stages:
  - test

jest:
  stage: test
  script:
    - yarn test --testTimeout=15000
  artifacts:
    reports:
      junit: junit.xml
